### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by louismosotho6** [KatlehoWMphuthi/Wits_Social#17]
Text camouflages with background when using dark mode - must change into solid color.

**Comment by KatlehoWMphuthi** [comment]
The screens are white in dark mode now.
![Screenshot_2022-04-22-15-25-15-39_d4a71ac4a23a403ee298ab1661ec47c2 1](https://user-images.githubusercontent.com/101892198/164724594-0e946eeb-e03c-4346-a544-798c4f92fc6e.jpg)

**Comment by mr-vance** [comment]
I also think that removing/disabling the Dark Mode functionality at this stage would be a very good idea.

I have updated the app so it remains in light mode at all times. 
Let me know if this is a good solution?
