### ISSUE TITLE
Landscape Mode 

### ISSUE THREAD

**Issue by KatlehoWMphuthi** [KatlehoWMphuthi/Wits_Social#20]
The user interface gets completely distorted in landscape mode. The only thing that works in landscape mode is the splash screen. 
![Screenshot_2022-04-22-15-26-57-34_d4a71ac4a23a403ee298ab1661ec47c2 1](https://user-images.githubusercontent.com/101892198/164725586-0d13ac62-9ae6-4c7c-97bc-a69bc6a7d471.jpg)

![Screenshot_2022-04-22-15-27-15-87_d4a71ac4a23a403ee298ab1661ec47c2 1](https://user-images.githubusercontent.com/101892198/164725338-7d96a148-dc11-41bb-bbf3-85606de19069.jpg)

**Comment by mr-vance** [comment]
Hi Kat..
Thanks for bringing this to our attention.
We'll work on it :)

**Comment by mr-vance** [comment]
Getting all the screens and their individual elements to work with landscape mode is going to be a bit of a pain in the arse.
I've been thinking about this and I realized that we could just disable auto-rotation for the app. That is, allow the app to work in portrait mode only.

Lemme know if this is okay?
