### ISSUE TITLE
Crashing App 

### ISSUE THREAD

**Issue by KatlehoWMphuthi** [KatlehoWMphuthi/Wits_Social#39]
I pulled the changes from @Kgotso and the app crashes the moment I enter the application

**Comment by KatlehoWMphuthi** [comment]
The application no longer crashes.

**Comment by kgotso** [comment]
For record keeping purposes, I am not assigned or related to this project at all. it would seem that @KatlehoWMphuthi  meant to mention @KgotsoKP  but accidently mentioned my name.
